name: release

on:
  push:
    branches: [main]
    tags: ['v*']
    paths:
      - 'src/**'
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "releasing..."
